apiVersion: apps/v1
kind: Deployment
metadata:
    name: persistent
spec:
    replicas: 2
    selector:
       matchLabels:
          app: persistent-app
    template:
       metadata:
          labels:
             app: persistent-app
       spec:
          containers:
          - name: app
            image: mongo_kub2_app:v1
            ports:
              - name: web
                containerPort: 80
            volumeMounts:
              - name: storage
                mountPath: /storage/
          volumes:
          - name: storage
            persistentVolumeClaim:
              claimName: storage

