apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: mongo-app
    template:
       metadata:
          labels:
             app: mongo-app
       spec:
          containers:
          - name: mongo-app
            image: mongo_kub2_app:v1
            ports:
              - name: web
                containerPort: 80
            env:
              - name: MONGO_HOST
                valueFrom:
                  configMapKeyRef:
                    name: mongo-config
                    key: MONGO_HOST


